name: Makefile CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - group: extensions
            module: aextsql
          - group: extensions
            module: example
          - group: extensions
            module: meta
          - group: extensions
            module: service
          - group: extensions
            module: text
          - group: extensions
            module: xml

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            qt4-qmake \
            libqt4-dev \
            libqt4-sql-sqlite \
            libqt4-sql-mysql \
            libqt4-sql-psql

      - name: Build module
        run: |
          cd src/${{ matrix.group }}/${{ matrix.module }}
          qmake-qt4
          make -j1
